version: '3'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: HackerTzy1337
      MYSQL_DATABASE: social_media
      MYSQL_USER: zakirkun
      MYSQL_PASSWORD: SecretBase112233
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - infrastructure
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - infrastructure
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=zakirkun
      - MINIO_ROOT_PASSWORD=MinioHackM31332
      - MINIO_DEFAULT_BUCKETS=social_media
  rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management Plugin port
    environment:
      - RABBITMQ_DEFAULT_USER=zakirkun
      - RABBITMQ_DEFAULT_PASS=zakir123
    networks:
      - infrastructure
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - infrastructure
    volumes:
      - redis_data:/data


networks:
  infrastructure:
    driver: bridge

volumes:
  mysql_data:
  minio_data:
  rabbitmq_data:
  redis_data: